### ISSUE TITLE
Crash on dropping items

### ISSUE THREAD

**Issue by Melakion** [joekaiser/QuantumFlux#95] opened 2016-04-01 16:47 UTC
QuantumFlux 2.0.3 - Forge 1816

http://pastebin.com/8Nx7rH4N

**Comment by kreezxil** [comment] 2016-04-01 18:55
Confirmed! Same thing happened to me. The error is client side. The server did not crash. 1.9 build 1816

http://paste.ee/p/e9EM7

**Comment by joekaiser** [comment] 2016-04-01 19:17
Something must have changed in the latest forge then. If possible, can you try with 1802?

**Comment by kreezxil** [comment] 2016-04-01 19:50
Here is another one that happened when taking items out of the inventory and throwing them away while on the inventory screen.

http://paste.ee/p/eW6wq

I personally can't try it with 1802 as all of the 147 mods in my pack will die.

**Comment by joekaiser** [comment] 2016-04-01 19:52
That's ok.Something in forge probably changes since 1802. I should be able to fix it this weekend

**Comment by joekaiser** [comment] 2016-04-01 19:54
Copying the main error here in case the paste expires

`java.lang.IllegalAccessError: tried to access field net.minecraftforge.event.entity.EntityEvent.entity from class jotato.quantumflux.registers.EventRegister
	at jotato.quantumflux.registers.EventRegister.onItemToss(EventRegister.java:17)`

**Comment by kwpugh** [comment] 2016-04-02 14:41
same here.

**Comment by joekaiser** [comment] 2016-04-04 03:30
Just an update. I have a fix for this, but it looks like block registration also changed in the newer versions of forge. I'll need to figure that out before I publish a fix

**Closed** 2016-04-04 17:18 UTC
Labels: bug

**Comment by joekaiser** [comment] 2016-04-04 18:48
uploading a patch to curse now. It should be available soon

**Comment by kwpugh** [comment] 2016-04-04 18:53
Thank you.   I will test it out.

**Comment by joekaiser** [comment] 2016-04-04 18:56
Link: http://minecraft.curseforge.com/projects/quantumflux/files/2292187

Note: I moved to java 7, and targeted forge 1836

**Comment by kwpugh** [comment] 2016-04-04 18:57
Running on Java 8 isn't going to be a problem, is it?

**Comment by joekaiser** [comment] 2016-04-04 18:59
Shouldn't be. I was on java 6 until just now.

**Comment by kwpugh** [comment] 2016-04-04 18:59
It seems to work fine on Java 8.

So what's the receipt for the ham and cheese sandwich (not in JEI)?

Great work, thank you.

**Comment by joekaiser** [comment] 2016-04-04 19:01
it is a rare drop from pigs :pig2:
