### ISSUE TITLE
Item duplication bug with the magnet

### ISSUE THREAD

**Issue by KaseiFR** [joekaiser/QuantumFlux#115] opened 2016-11-19 16:41 UTC
Submitting a bug report? Please fill out the form below the best you can.

*Version:* 1.10.2-2.0.9

*Mod pack:* Hermitpack 1.4

*Summary:* Item duplication bug with the magnet and a hopper

____

####What is happening? When breaking a block on top of a hopper, its item form is both grabbed by the hopper and the magnet on the player, resulting in a duplicate.

####How do you think it should be? Only the hopper OR the player should get the block item.

####How can I reproduce the problem? Put a block on top of a hopper, have an activated item magnet, and break the block.

**Comment by joekaiser** [comment] 2016-11-20 00:48
Duplicate of #102

**Closed by joekaiser** 2016-11-20 00:48 UTC
Labels: bug, duplicate
