### ISSUE TITLE
Duplication Bug with the magnet

### ISSUE THREAD

**Issue by SwatKid** [joekaiser/QuantumFlux#102] opened 2016-04-30 15:57 UTC
When a block is on a hopper and you break the block with a magnet active the block will go into the hopper and your inventory creating a total of 2 blocks.

**Comment by joekaiser** [comment] 2016-05-01 14:07
Which version? 1.7 or 1.9?

**Comment by SwatKid** [comment] 2016-05-01 19:39
1.9

**Comment by joekaiser** [comment] 2016-05-01 23:24
I can't reproduce this. Are you in a server or local? can you make it happen every time? What other mods are installed? Any detail (you can't give too much) will help me

**Comment by SwatKid** [comment] 2016-05-02 13:59
Local and it is everytime and i tested it with only QuantumFlux installed. Video of the bug https://gfycat.com/HideousLazyGrasshopper

**Comment by joekaiser** [comment] 2016-05-03 17:45
one more question. which version of forge are you using?

**Comment by joekaiser** [comment] 2016-05-03 20:20
Thanks, fixed it :) It will be part of 2.0.6+

**Comment by joekaiser** [comment] 2016-05-03 20:42
Reopened because I was stupid and my "fix" broke the magnet :anguished:

**Comment by ButtonBright0907** [comment] 2016-09-06 13:30
I found that this bug can be used to duplicate stacks of items as well. Simply look at the center of the hopper as you toss a stack from your inventory. you have to be real close to the hopper for this to work though.

**Comment by joekaiser** [comment] 2016-11-20 00:47
This should still be open. Not sure why it is closed

**Comment by b0bst3r** [comment] 2016-12-08 02:54
Way to fix this is when an item is thrown by the player it has a time delay to picking it back up. From all the testing I have done this is how all the other magnets seem to be working.

**Comment by joekaiser** [comment] 2016-12-08 16:16
That wouldn't cover all use-cases; not to mention I specifically don't want the behavior. My guess it an event was changed/added and I just need to find time to track it down.

**Closed** 2016-12-22 22:23 UTC
Labels: bug

**Comment by b0bst3r** [comment] 2016-12-28 01:12
This isn't fixed at all, tried it with 2.0.10 and a hopped and duping still occurs.

**Comment by joekaiser** [comment] 2016-12-28 17:29
I'm not sure what happened. it was fixed; but it really should be now :)

**Comment by ShadowsVengeance** [comment] 2017-02-06 22:11
Seems to still be the case for me, latest version.

https://youtu.be/94VzLv3Zj-Y

http://prntscr.com/e5e6xl

**Comment by joekaiser** [comment] 2017-02-09 01:01
What modpack? Do you have anything like FastCraft, Optifine, CoFH Tweaks for BetterFPS installed?

**Comment by ShadowsVengeance** [comment] 2017-02-09 01:12
Using allthemods 1.10.2, I think i added quantumflux, it has foamfix
installed.
