### ISSUE TITLE
Battlesuit Blackout

### ISSUE THREAD

**Issue by bert1085** [joekaiser/QuantumFlux#104] opened 2016-05-04 23:56 UTC
I upgraded my battlesuit helmet with vision and now I have a permanent black out every time I put it on. I'm playing the Galactic Science modpack with MC 1.7.10

**Comment by joekaiser** [comment] 2016-05-05 16:34
if you take a night vision potion, does the same thing happen?

**Comment by joekaiser** [comment] 2016-05-31 20:24
any word on this, or is it OK to close it? I have tried on 3 computers and can't reproduce it

**Comment by bert1085** [comment] 2016-06-01 00:50
Ok, thanks for looking into it.

Sent using OWA for iPhone
________________________________

**Comment by joekaiser** [comment] 2016-06-01 02:27
no-repro. Will re-open if this turns out to be a bug

**Closed by joekaiser** 2016-06-01 02:27 UTC
Labels: invalid
